export const cottonColors = [
  { name: "Aquatic Blue", hex: "#53BAE5" },
  { name: "Ash", hex: "#DFDEE4" },
  { name: "Athletic Heather", hex: "#B7B3BA" },
  { name: "Athletic Maroon", hex: "#5D1A24" },
  { name: "Bright Aqua", hex: "#0B8C89" },
  { name: "Candy Pink", hex: "#FEB3D0" },
  { name: "Cardinal", hex: "#8D1D2D" },
  { name: "Carolina Blue", hex: "#6F99D8" },
  { name: "Charcoal", hex: "#434242" },
  { name: "Clover Green", hex: "#0E9C5A" },
  { name: "Coyote Brown", hex: "#977F5F" },
  { name: "Dark Chocolate Brown", hex: "#4E2E2D" },
  { name: "Dark Green", hex: "#13332C" },
  { name: "Dark Heather Grey", hex: "#575757" },
  { name: "Gold", hex: "#FDC35C" },
  { name: "Graphite Heather", hex: "#737373" },
  { name: "Heather Athletic Maroon", hex: "#5D2732" },
  { name: "Heather Dark Chocolate Brown", hex: "#4E2E2D" },
  { name: "Heather Navy", hex: "#344055" },
  { name: "Heather Purple", hex: "#2D2B6C" },
  { name: "Heather Red", hex: "#933645" },
  { name: "Heather Royal", hex: "#5970C9" },
  { name: "Heather Sangria", hex: "#E76AA0" },
  { name: "Jet Black", hex: "#282828" },
  { name: "Kelly", hex: "#0A885D" },
  { name: "Light Blue", hex: "#A7BDE2" },
  { name: "Lime", hex: "#A5C350" },
  { name: "Medium Grey", hex: "#8B8788" },
  { name: "Natural", hex: "#F1E9D5" },
  { name: "Navy", hex: "#113551" },
  { name: "Neon Blue", hex: "#1183AC" },
  { name: "Neon Green", hex: "#33CF66" },
  { name: "Neon Orange", hex: "#FC7253" },
  { name: "Neon Pink", hex: "#FA6288" },
  { name: "Neon Yellow", hex: "#D9E562" },
  { name: "Olive", hex: "#434A3B" },
  { name: "Olive Drab Green", hex: "#615D46" },
  { name: "Orange", hex: "#E15A27" },
  { name: "Purple", hex: "#353377" },
  { name: "Red", hex: "#822B38" },
  { name: "Royal", hex: "#2F4C92" },
  { name: "Sand", hex: "#B39A88" },
  { name: "Sangria", hex: "#D35785" },
  { name: "Sapphire", hex: "#0D85BA" },
  { name: "Silver", hex: "#D2D3D7" },
  { name: "Steel Blue", hex: "#3C4F5F" },
  { name: "Teal", hex: "#07657B" },
  { name: "Team Purple", hex: "#5E4084" },
  { name: "True Royal", hex: "#30479E" },
  { name: "White", hex: "#FDFDFC" },
  { name: "Woodland Brown", hex: "#917257" },
  { name: "Yellow", hex: "#F7DD79" }
];

